version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=$3nh4F0rt3
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
