version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=$3nh4F0rt3
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
